### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by LaPeSi** [luigman/obsidian-vextab#1]
I just tried your plugin. I like it a lot and I think it's better than jTab.
Unfortunately, there is one thing that bothers me, the tabs are only available in light mode (as far as I can tell).
I would love to see a setting similar to jTab, where I can change the colors.

As a workaround this css snippet inverts the colors:
```css
.block-language-vextab{
  filter: invert(88.4%) hue-rotate(180deg);
}
```

Regards :)
